### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cchwala** [OpenSenseAction/merging_prototype#1]
Goal for meeting in Prague:
- [x] working example notebook that can be run locally
- [x] (maybe run online via binder)
- [x] use imports from `poligrain` instead of old `ragali` prototype functions (currently done via `poligrain` as git submodule using WIP branch from https://github.com/OpenSenseAction/poligrain/pull/41)

Next steps till end of April:
- [x] @cchwala cleans up `poligrain` code and finalize https://github.com/OpenSenseAction/poligrain/pull/41
- [ ] Others test out variations of the current notebook with own data and/or own methods
- [ ] Discuss way forward and goals for meeting in Milano in June 2024 during video call in early May

**Comment by cchwala** [comment]
We do not continue development here because we have already, based on the initial work in this repo, started with [`mergeplg`](https://github.com/OpenSenseAction/mergeplg) which shall hold all future implementations.
